### ISSUE TITLE
ERROR: [windows] No matching distribution found for torch==2.1.1+cu121

### ISSUE THREAD

**Issue by likhith00** [Teddy-XiongGZ/MedRAG#1]
**os:** Windows11

**Python version:** Python 3.10.11

**issue description:**

Installing `pip install -r requirements.txt` throws error: No matching distribution found for torch==2.1.1+cu121

**Comment by likhith00** [comment]
solved by running ```pip install torch==2.1.0+cu121 -f https://download.pytorch.org/whl/torch_stable.html``` in command prompt

**Comment by gzxiong** [comment]
Thanks for letting me know! I've corrected `requirements.txt` and updated the Requirements section in `README.md`.
