### ISSUE TITLE
Integrating a New Retriever into MedRAG for MIRAGE Benchmark

### ISSUE THREAD

**Issue by hajhouj** [Teddy-XiongGZ/MedRAG#13]
First of all, I would like to congratulate you on the high quality of your work on MedRAG and the MIRAGE benchmark. Your systematic approach and comprehensive evaluations are well done and useful to the field.  I am currently working on a new retriever for medical question answering, and I am interested in integrating my retriever into the MedRAG toolkit for benchmarking on the MIRAGE dataset. Could you please guide me on how to do this?

**Comment by gzxiong** [comment]
Hi! Thanks for your interest in our work. To add a new retriever into MedRAG, here are the detailed instructions:
1. Add your retriever name and the corresponding path on HF to https://github.com/Teddy-XiongGZ/MedRAG/blob/main/src/utils.py#L19
2. Add the retriever-specific method to pre-process a chunk for embedding: https://github.com/Teddy-XiongGZ/MedRAG/blob/main/src/utils.py#L77
3. Check if the Index type is correct: https://github.com/Teddy-XiongGZ/MedRAG/blob/main/src/utils.py#L93
4. Check if the query embedding process is ok: https://github.com/Teddy-XiongGZ/MedRAG/blob/main/src/utils.py#L166
5. (optional) To include the new retriever in RRF, please
- - Add the new RRF method with the new retriever in the list (#L77)
- - Check if the order is correct for sorting scores (#L236)

**Comment by hajhouj** [comment]
Thank you for the detailed instructions, I appreciate your quick response :). I will follow the steps you've provided to integrate my retriever into MedRAG. If I encounter any issues, I'll reach out for further guidance.
