### ISSUE TITLE
Request the retrieval results of the datasets

### ISSUE THREAD

**Issue by jinniulema** [Teddy-XiongGZ/MedRAG#14]
Hello, we greatly appreciate your outstanding work. Could you provide the retrieved fragments for each dataset obtained using RRF4-MedCorp? You said in issue https://github.com/Teddy-XiongGZ/MedRAG/issues/10#issuecomment-2163965722 that you will provide that in June. But I couldn't find the location of the relevant data. Did I miss something?

**Comment by gzxiong** [comment]
Since the retrieval results are relevant to specific datasets, we place them in the repo of our MIRAGE benchmark. You can find the description here: https://github.com/Teddy-XiongGZ/MIRAGE

**Comment by jinniulema** [comment]
Thanks for your reply.
