### ISSUE TITLE
Token indices sequence length is longer

### ISSUE THREAD

**Issue by TxTmiaopasi** [Teddy-XiongGZ/MedRAG#17]
When using the pmc_llam model, a warning appears: 
Token indices sequence length is longer than the specified maximum sequence length for this model (8778 > 512). Running this sequence through the model will result in indexing errors.
Does this warning affect the accuracy of the results? If so, how should I set it?

![捕获](https://github.com/user-attachments/assets/13cf2609-434b-4029-ac94-f0e30d79ec61)

**Comment by gzxiong** [comment]
According to their config file (https://huggingface.co/axiong/PMC_LLaMA_13B/blob/main/config.json), the maximum sequence length should be 2k for PMC-LLaMA-13B. It should be fine if the warning occurs because of PMC-LLaMA itself.

p.s., 512 looks like the maximum length of BERT-based models.
