### ISSUE TITLE
Repeated Generation in Llama 3.1 & 3.2 Models

### ISSUE THREAD

**Issue by dbsxfz** [Teddy-XiongGZ/MedRAG#25]
I've encountered an issue with both Llama 3.1 and 3.2 models where they tend to generate repeated text, especially when the generation reaches the maximum length (128K tokens). 
To avoid this issue, I recommend adding the repetition_penalty parameter with a value of 1.2 and limiting the max_new_tokens to 4096 tokens or fewer. This combination should help mitigate the issue of repeated generation and reduce lag.

**Comment by jhnwu3** [comment]
I've also encountered this issue and I have found that I am unable to replicate their 77.23% accuracy for CoT on MMLU-Med, and typically get around 20% acc with llama 3.1 8B instruct.
<img width="918" alt="image" src="https://github.com/user-attachments/assets/ff7ae2d0-b6ae-472f-b522-34791c28b629">

**Comment by jhnwu3** [comment]
Follow up on it: You may have to do some tinkering with the locate_answer() function too, because the extracted answer may not actually be what the model has generated.

**Comment by gzxiong** [comment]
Hi @dbsxfz, thank you for your suggestions! We have now added "**kwargs" to support custom argument configurations. This would be more flexible for users to try different argument values.

**Comment by gzxiong** [comment]
Hi @jhnwu3, thanks for reporting this issue! I've just tested our CoT setting on the demo question in README (which is also from MMLU-Med). The result seems okay and has a clear structure that can be easily parsed. Could you please give me more details of what errors you see with our implemented CoT? For example, does the model fail to present its output in a structured way? Or is it just outputting wrong predictions?

By the way, we used "meta-llama/Meta-Llama-3.1-8B-Instruct" when running the experiments. I noticed that its official name has been changed to "meta-llama/Llama-3.1-8B-Instruct" on HuggingFace. Not sure if there are any changes in its parameters. (I just tried the latest checkpoint and it seems to have the same output as our previously downloaded checkpoint)

**Comment by jhnwu3** [comment]
Hey Teddy, so, some of the changes I made was more related to your MIRAGE benchmark (https://github.com/Teddy-XiongGZ/MIRAGE/blob/main/src/evaluate.py) rather than the code here. 

Specifically, I changed the locate_answer function to the following:

`
def locate_answer(sentence: str, options: dict = None):
    """
    Locate the answer choice (A/B/C/D) from a model output string using various patterns.
    If no pattern matches and options are provided, falls back to entity matching.
    
    Args:
        sentence (str): The raw model output to search for an answer
        options (dict, optional): Dictionary mapping answer choices to entities
                                e.g., {"A": "entity1", "B": "entity2", ...}
    
    Returns:
        str: The located answer choice (A/B/C/D), defaults to "A" if no match found
    """
    # List of regex patterns to try
    patterns = [
        r'^\s*(A|B|C|D)$',
        r'^\s*(A|B|C|D) or',
        r'^\s*(A|B|C|D) and',
        r'^\s*(A|B|C|D)/',
        r'^\s*(A|B|C|D),',
        r'[Oo]ption (A|B|C|D)',
        r':\s*(A|B|C|D)',
        r'^\s*(A|B|C|D)\.',
        r'^\s*(A|B|C|D)"',
        r'^\s*(A|B|C|D):',
        r'[Tt]he answer is (A|B|C|D)',
        r'answer is (A|B|C|D)\)',
        r'(A|B|C|D)\)',
        r'^\s*(A|B|C|D)\)',
        r'"answer_choice":\s*"([A-D])',  # New pattern for JSON-like format
        r'"answer":\s*"([A-D])'          # Alternative JSON-like format
    ]
    
    # Try each pattern
    for pattern in patterns:
        ans = re.findall(pattern, sentence)
        if len(ans) > 0:
            return ans[0].upper() if isinstance(ans[0], str) else ans[0][0].upper()
    
    # If no pattern matched and options are provided, try entity matching
    if options:
        # Get the last occurrence of each entity in the text
        entity_positions = {}
        for choice, entity in options.items():
            # Skip empty entities
            if not entity.strip():
                continue
            # Find all occurrences of the entity
            matches = [m.start() for m in re.finditer(re.escape(entity), sentence, re.IGNORECASE)]
            if matches:
                entity_positions[choice] = max(matches)  # Keep the last occurrence
        
        # If we found any entities
        if entity_positions:
            # If only one entity was found, return that choice
            if len(entity_positions) == 1:
                return list(entity_positions.keys())[0].upper()
            # If multiple entities found, return the one that appears last
            if len(entity_positions) > 1:
                return max(entity_positions.items(), key=lambda x: x[1])[0].upper()
    
    return "A"  # Default fallback
`


There were a couple weird edge cases where the LLMs I was testing like the medically finetuned llama 3 (https://huggingface.co/aaditya/Llama3-OpenBioLLM-70B) or llama 3.1 earlier where it wouldn't generate a letter, but rather just the option entity. Like instead of "the answer is A) entity", it would give "the answer is entity".

**Comment by gzxiong** [comment]
@jhnwu3 Thanks for sharing this! It seems like the model may not faithfully follow the user instructions. One possible way to address this problem is to use a small LLM (or the current LLM) to extract the answer and output it in a JSON format: {"answer_choice": your_answer (A/B/C/D)}. This should enhance the robustness of the answer extraction (though at the cost of less efficiency).
