### ISSUE TITLE
Textbooks chunks seem to be duplicated

### ISSUE THREAD

**Issue by JuaniTollo** [Teddy-XiongGZ/MedRAG#28]
At https://huggingface.co/datasets/MedRAG/textbooks, the contents include both content and title. Later, when providing snippets to the LLM, you are passing both content and contents. I might be missing something, but it seems like the chunk is being duplicated.

**Comment by JuaniTollo** [comment]
The LLM is only receiving the content and the title at the end.

**Comment by gzxiong** [comment]
The 'contents' column is kept for the purpose of building BM25 index.
