### ISSUE TITLE
Retrieval Speed

### ISSUE THREAD

**Issue by YueYANG1996** [Teddy-XiongGZ/MedRAG#5]
Thanks for the great work, it is super useful!

How long does it take to retrieve documents for one query using PubMed as the database? It seems to take me very long. Is there any way to improve the efficiency?

Thank you!

Yue

**Comment by gzxiong** [comment]
I didn't measure this. But it may take around 3 minutes if you use the combination of all corpora (MedCorp) and all retrievers (RRF-4) on A100 GPUs for an end-to-end RAG. It would be much quicker if you use single retrievers.

Using GPU can accelerate this process for sure. For the retrieval phase, you may also replace L82 and L84 in src/utils.py with some approximate indexer in faiss for efficient similarity search.
