### ISSUE TITLE
Prompt template for single document on medical QA with MEDRAG 

### ISSUE THREAD

**Issue by jw-sohn** [Teddy-XiongGZ/MedRAG#6]
Hello @Teddy-XiongGZ 

Thank you for your awesome work. I am really impressed by the scale of experiments you and your team have conducted. 

I have one small question

The example template that is mentioned in the paper and the GitHub is

```
Here are the relevant documents:
{{context}}
```
I wonder if you used this for using single retrieved snippet setting as well, instead of using 

"""
Here is a relevant document:
"""

**Comment by gzxiong** [comment]
Thank you for your interest in our work! We did use the same template when using a single retrieved snippet. Before being entered into the templates, all snippets will be indexed as shown in https://github.com/Teddy-XiongGZ/MedRAG/blob/main/src/medrag.py#L93.
