### ISSUE TITLE
MedCPT max_length

### ISSUE THREAD

**Issue by P-YI** [Teddy-XiongGZ/MedRAG#7]
Hi.

First of all, thank you for your work.

I would like to know that it is possible to change the max length of the ncbi/MedCPT-Query-Encoder when retrieve and get documents.
When I look up the code, I couldn't find any parameters that could be adjustable.
So then, is it right that it would use the basic parameter of MedCPT when it is loaded by class CustomizeSentenceTransforme?
Or is there any other way to change max length of MedCPT?

**Comment by gzxiong** [comment]
MedCPT is built based on PubMedBERT, which has a maximum input length of 512 tokens (same as BERT-base).

We did not adjust this hyperparameter. Instead, we chunked the corpus into small pieces to fit this constraint.
